config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  get 'home/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'carts/show'
  # get 'carts/update'
  # get 'carts/remove'
  # get 'products/index'
  # get 'products/show'

  resources :types do
    resources :products, only: :index
  end

  resources :brands do
    resources :products, only: :index
  end

  resources :categories do
    resources :products, only: :index
  end

  resources :tags do
  resources :products, only: [:index, :show]
end


  resources :products, only: [:index, :show] do
    collection do
      get 'filter'
      get 'filter_by_category'
      get "search"
    end

    member do
      post 'add_to_cart'
    end
  end

  get 'cart', to: 'carts#show'
  put 'cart/update', to: 'carts#update'
  delete 'cart/remove', to: 'carts#remove'
  get 'pages/:permalink', to: 'pages#permalink', as: 'permalink'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

         def self.ransackable_attributes(auth_object = nil)
          ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
        end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order_items
  has_many :products, through: :order_items

  validates :order_date, presence: true
  validates :GST, :HST, :PST, :total_amount, numericality: { greater_than_or_equal_to: 0 }
  validates :status, inclusion: { in: %w[pending paid shipped] }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :type
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeupHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<div class="container">
  <h1><%= @page.title %></h1>
  <p><%= @page.content.html_safe %></p>
</div>

app/views/shared/_footer.html.erb
<footer class="footer has-background-dark">
  <div class="container">
    <div class="columns">
      <div class="column">
        <h3 class="footer-title title is-6  has-text-white">Makeup Hub</h3>
        <p class="footer-content is-size-7 has-text-white">Welcome to Makeup Hub! We are your one-stop destination for high-quality makeup products and beauty accessories. Our mission is to enhance your natural beauty and help you express your unique style through our curated collection of products. Stay fabulous with Makeup Hub!</p>
      </div>
      <div class="column is-centered">
        <h3 class="footer-title title is-6  has-text-white">Explore</h3>
        <ul class="footer-links">
          <li class="is-size-7"><%= link_to 'Home', root_path, class: 'has-text-white' %></li>
          <li class="is-size-7"><%= link_to 'Products', products_path, class: 'has-text-white' %></li>
          <li><%= link_to 'About Us', permalink_path('about_us'), class: 'has-text-white is-size-7' %></li>
          <li><%= link_to 'Contact Us', permalink_path('contact_us'), class: 'has-text-white is-size-7' %></li>
        </ul>
      </div>
      <div class="column">
        <h3 class="footer-title title is-6  has-text-white">Follow Us</h3>
        <p class="footer-social">
          <a href="#" class="is-size-4 "><i class="fab fa-facebook"></i></a>
          <a href="#" class="is-size-4 "><i class="fab fa-twitter"></i></a>
          <a href="#" class="is-size-4 "><i class="fab fa-instagram"></i></a>
        </p>
      </div>
    </div>
  </div>

  <div class="container mt-6">
    <div class="footer-bottom has-text-centered">
      <p class="is-size-7 has-text-white">Conditions of Use | Privacy Notice </p>
      <p class="is-size-7 has-text-white">© 2023 Makeup Hub. All rights reserved. Designed by Maryam Designs.</p>
    </div>
  </div>
</footer>

app/views/shared/_menu.html.erb
<nav class="navbar is-dark"  aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="<%= root_path %>">MAKEUP HUB</a>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
      data-target="navbarNav">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu has-background-dark" id="navbarNav">
    <div class="navbar-start ">
      <a class="navbar-item has-text-white" href="<%= root_path %>">Products</a>

      <%
=begin%>
 <a class="navbar-item has-text-white" href="<%= planets_path %>">About Us</a>
      <a class="navbar-item has-text-white" href="<%= about_path %>">Contact Us</a>
<%
=end%>
    </div>
     <div class="navbar-end">
      <%= form_tag(products_path, method: :get, class: 'navbar-item') do %>
        <div class="select is-dark">
          <%= select_tag(:type_id, options_for_select(Type.all.map { |t| [t.name, t.id] }), include_blank: 'All Types') %>
        </div>
        <div class="buttons">
          <%= submit_tag('Search', class: 'button is-primary') %>
        </div>
      <% end %>
      <%= form_tag(products_path, method: :get, class: 'navbar-item') do %>
        <div class="buttons">
          <%= check_box_tag(:new, true) %>
          <label for="new">New</label>
          <%= check_box_tag(:recently_updated, true) %>
          <label for="recently_updated">Recently Updated</label>
          <%= check_box_tag(:on_sale, true) %>
          <label for="on_sale">On Sale</label>
          <%= submit_tag('Filter', class: 'button is-primary') %>
        </div>
      <% end %>
    </div>
    <%
=begin%>
 <%= form_tag(search_people_path, method: :get,  class: 'navbar-end') do %>
      <div class="navbar-item has-background-dark">
        <%= text_field_tag(:name, params[:name], id: 'name-input', placeholder: 'Search by Name', class: 'input') %>
      </div>
      <div class="navbar-item has-background-dark">
        <%= select_tag(:species_id, options_for_select(Species.all.map { |s| [s.name, s.id] }, params[:species_id]), include_blank: 'All Species', default: nil, class: 'select') %>
      </div>
      <div class="navbar-item has-background-dark">
        <%= submit_tag('Search', class: 'button is-primary') %>
      </div>
    <% end %>
<%
=end%>
  </div>


</nav>