config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  get 'home/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'carts/show'
  # get 'carts/update'
  # get 'carts/remove'
  # get 'products/index'
  # get 'products/show'

  resources :types do
    resources :products, only: :index
  end

  resources :brands do
    resources :products, only: :index
  end

  resources :categories do
    resources :products, only: :index
  end

  resources :tags do
  resources :products, only: [:index, :show]
end


  resources :products, only: [:index, :show] do
    collection do
      get 'filter'
      get 'filter_by_category'
      get "search"
    end

    member do
      post 'add_to_cart'
    end
  end

  get 'cart', to: 'carts#show'
  put 'cart/update', to: 'carts#update'
  delete 'cart/remove', to: 'carts#remove'
  get 'pages/:permalink', to: 'pages#permalink', as: 'permalink'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

         def self.ransackable_attributes(auth_object = nil)
          ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
        end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order_items
  has_many :products, through: :order_items

  validates :order_date, presence: true
  validates :GST, :HST, :PST, :total_amount, numericality: { greater_than_or_equal_to: 0 }
  validates :status, inclusion: { in: %w[pending paid shipped] }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :type
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def show
    @page = Page.find_by(title: params[:slug])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_filter.html.erb
<div class="container">
        <%= form_tag(filter_products_path, method: :get, class: 'navbar-item') do %>
                <div class="buttons">
                <%= check_box_tag(:new, true) %>
                <label for="new">New</label>
                <%= check_box_tag(:recently_updated, true) %>
                <label for="recently_updated">Recently Updated</label>
                <%= check_box_tag(:on_sale, true) %>
                <label for="on_sale">On Sale</label>
                <%= submit_tag('Filter', class: 'button is-primary') %>
                </div>
            <% end %>

        <%= form_tag(filter_products_path, method: :get, class: 'navbar-item') do %>
            <div class="select is-dark">
            <%= select_tag(:type_id, options_for_select(Type.all.map { |t| [t.name, t.id] }), include_blank: 'All Categories') %>
            </div>
            <div class="buttons">
            <%= submit_tag('Search', class: 'button is-primary') %>
            </div>
        <% end %>
    </div>

app/views/products/_product.html.erb
<div>
<h1><%= @product.name %></h1>
<p>Brand: <%= @product.brand.name %></p>
<p>Type: <%= @product.type.name %></p>
<p>Category: <%= @product.category.name %></p>
<p>Price: <%= @product.price %></p>
<p>Description: <%= @product.description %></p>
<p>On Sale: <%= @product.on_sale_status ? 'Yes' : 'No' %></p>
<% if @product.image.attached? %>
  <p>Image:</p>
  <%= image_tag @product.image %>
<% end %>
</div>

app/views/products/filter.html.erb
<h1>Products</h1>

<% if params[:type_id].present? %>
  <p>Current Filter: Category - <%= Type.find(params[:type_id]).name %></p>
<% elsif params[:new].present? %>
  <p>Current Filter: New Products</p>
<% elsif params[:recently_updated].present? %>
  <p>Current Filter: Recently Updated Products</p>
<% elsif params[:on_sale].present? %>
  <p>Current Filter: On Sale Products</p>
<% else %>
  <p>All Products</p>
<% end %>

<% @products.each do |product| %>
  <h3><%= product.name %></h3>
  <!-- Display other product details as desired -->
<% end %>

app/views/products/filter_by_category.html.erb
<div class="container">
  <%= render partial: 'filter' %>
  <%= paginate @products %>

  <% if params[:type_id].present? %>
    <% if @products.any? %>
      <h3 class="title is-5"> Category - <%= Type.find(params[:type_id]).name %></h3>

      <div class="columns is-multiline">
        <% @products.each do |product| %>
          <%= render product %>
        <% end %>
      </div>
    <% else %>
      <p>No products found in this category.</p>
    <% end %>
  <% else %>
    <h3 class="title is-5">All Categories</h3>

    <div class="columns is-multiline">
      <% @products.each do |product| %>
        <%= render product %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/products/type.html.erb
<h1>Products in Type: <%= @type.name %></h1>
<% @products.each do |product| %>
  <h3><%= product.name %></h3>
  <!-- Display other product details as desired -->
<% end %>