config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  get 'home/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'carts/show'
  # get 'carts/update'
  # get 'carts/remove'
  # get 'products/index'
  # get 'products/show'

  resources :types do
    resources :products, only: :index
  end

  resources :brands do
    resources :products, only: :index
  end

  resources :categories do
    resources :products, only: :index
  end

  resources :tags do
  resources :products, only: [:index, :show]
end


  resources :products, only: [:index, :show] do
    collection do
      get 'filter'
      get 'filter_by_category'
      get "search"
    end

    member do
      post 'add_to_cart'
    end
  end

  get 'cart', to: 'carts#show'
  put 'cart/update', to: 'carts#update'
  delete 'cart/remove', to: 'carts#remove'
  get 'pages/:permalink', to: 'pages#permalink', as: 'permalink'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

         def self.ransackable_attributes(auth_object = nil)
          ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
        end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order_items
  has_many :products, through: :order_items

  validates :order_date, presence: true
  validates :GST, :HST, :PST, :total_amount, numericality: { greater_than_or_equal_to: 0 }
  validates :status, inclusion: { in: %w[pending paid shipped] }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :type
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer! # This ensures that the user is logged in before accessing the actions
  before_action :find_customer, only: [:show, :edit, :update]

  def show
    # The customer details are already loaded in the before_action.
  end

  def edit
    # The customer details are already loaded in the before_action.
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer details updated successfully.'
    else
      render :edit
    end
  end

  private

  def find_customer
    @customer = current_customer
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :primary_address, :alt_address,
                                     :primary_city, :alt_city, :primary_postal_code, :alt_postal_code,
                                     :primary_province_id, :alt_province_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def show
    @page = Page.find_by(title: params[:slug])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customer/show.html.erb
<h1>Customer Details</h1>
<p><strong>First Name:</strong> <%= @customer.first_name %></p>
<p><strong>Last Name:</strong> <%= @customer.last_name %></p>
<p><strong>Email:</strong> <%= @customer.email %></p>
<p><strong>Primary Address:</strong> <%= @customer.primary_address %></p>
<p><strong>Alt Address:</strong> <%= @customer.alt_address %></p>
<p><strong>Primary City:</strong> <%= @customer.primary_city %></p>
<p><strong>Alt City:</strong> <%= @customer.alt_city %></p>
<p><strong>Primary Postal Code:</strong> <%= @customer.primary_postal_code %></p>
<p><strong>Alt Postal Code:</strong> <%= @customer.alt_postal_code %></p>
<p><strong>Primary Province:</strong> <%= @customer.primary_province.name if @customer.primary_province %></p>
<p><strong>Alt Province:</strong> <%= @customer.alt_province.name if @customer.alt_province %></p>

<% if customer_signed_in? %>
<%= link_to 'Edit Account Details', edit_customer_registration_path(current_customer), class: 'button is-primary' %>
<% end %>

app/views/customers/show.html.erb
<h1>Customer Details</h1>
<p><strong>First Name:</strong> <%= @customer.first_name %></p>
<p><strong>Last Name:</strong> <%= @customer.last_name %></p>
<p><strong>Primary Address:</strong> <%= @customer.primary_address %></p>
<p><strong>Alt Address:</strong> <%= @customer.alt_address %></p>
<p><strong>Primary City:</strong> <%= @customer.primary_city %></p>
<p><strong>Alt City:</strong> <%= @customer.alt_city %></p>
<p><strong>Primary Postal Code:</strong> <%= @customer.primary_postal_code %></p>
<p><strong>Alt Postal Code:</strong> <%= @customer.alt_postal_code %></p>
<p><strong>Primary Province:</strong> <%= @customer.primary_province.name if @customer.primary_province %></p>
<p><strong>Alt Province:</strong> <%= @customer.alt_province.name if @customer.alt_province %></p>
<%= link_to 'Edit Account Details', edit_customer_path(@customer), class: 'button is-primary' %>